package COSC_1436_summer25.Labs.Week4.Lab7;

public enum Affiliation
{
    AVENGERS,
    X_MEN,
    JUSTICE_LEAGUE,
    FANTASTIC_FOUR,
    TEEN_TITANS,
    JUSTICE_SOCIETY_OF_AMERICA,
    INHUMANS,
    GUARDIANS_OF_THE_GALAXY
}